import { useEffect, useState } from "react";
import { Check, Loader2, X } from "lucide-react";
import { formatErrorMessage } from "../../../shared/api";
import { AdminTutorCard, PageResponse, approveTutorCard, fetchTutorCardsForModeration, rejectTutorCard } from "../api";
import { AdminPagination } from "./AdminPagination";

const empty: PageResponse<AdminTutorCard> = { items: [], page: 1, limit: 20, total: 0, totalPages: 0 };

export function TutorCardModerationTab() {
  const [page, setPage] = useState(1); const [data, setData] = useState(empty); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<number | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); try { setData(await fetchTutorCardsForModeration(page)); } catch (reason) { setError(formatErrorMessage(reason instanceof Error ? reason.message : "", "Не удалось загрузить карточки")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page]);
  async function approve(id: number) { setBusy(id); try { await approveTutorCard(id); await load(); } catch (reason) { setError(formatErrorMessage(reason instanceof Error ? reason.message : "", "Не удалось одобрить карточку")); } finally { setBusy(null); } }
  async function reject(id: number) { const reason = window.prompt("Укажите причину отклонения карточки"); if (!reason?.trim()) return; setBusy(id); try { await rejectTutorCard(id, reason); await load(); } catch (value) { setError(formatErrorMessage(value instanceof Error ? value.message : "", "Не удалось отклонить карточку")); } finally { setBusy(null); } }
  return <section><div className="mb-5"><h2 className="text-xl font-semibold">Модерация карточек</h2><p className="text-sm text-muted-foreground">После одобрения активная карточка появится в поиске.</p></div>{error && <div className="mb-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{loading ? <div className="flex justify-center py-12"><Loader2 className="animate-spin" /></div> : <div className="space-y-3">{data.items.map((card) => <article key={card.id} className="rounded-2xl border border-border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{card.title}</div><div className="text-sm text-muted-foreground">{card.tutorFirstName} {card.tutorLastName} · {card.subject}</div></div><div className="font-medium">{card.pricePerLesson.toLocaleString("ru-RU")} ₽/час</div></div><p className="mt-3 text-sm text-muted-foreground">{card.description || "Описание не заполнено"}</p><div className="mt-3 text-xs text-muted-foreground">Классы: {card.supportedGrades.join(", ")} · формат: {card.format}</div><div className="mt-4 flex gap-2"><button disabled={busy === card.id} onClick={() => void approve(card.id)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm text-primary-foreground"><Check size={15} />Принять</button><button disabled={busy === card.id} onClick={() => void reject(card.id)} className="inline-flex items-center gap-2 rounded-xl border border-destructive/30 px-4 py-2 text-sm text-destructive"><X size={15} />Отклонить</button></div></article>)}{!data.items.length && <div className="py-10 text-center text-sm text-muted-foreground">Карточек на модерации нет</div>}</div>}<AdminPagination page={data.page} totalPages={data.totalPages} onChange={setPage} /></section>;
}
