import { useEffect, useState } from "react";
import { Check, Loader2, X } from "lucide-react";
import { formatErrorMessage } from "../../../shared/api";
import { PageResponse, TutorAccountApplication, approveTutorAccountApplication, fetchTutorAccountApplications, rejectTutorAccountApplication } from "../api";
import { AdminPagination } from "./AdminPagination";

const empty: PageResponse<TutorAccountApplication> = { items: [], page: 1, limit: 20, total: 0, totalPages: 0 };

export function TutorAccountApplicationsTab() {
  const [status, setStatus] = useState("PENDING"); const [page, setPage] = useState(1); const [data, setData] = useState(empty);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<number | null>(null);
  async function load() { setLoading(true); try { setData(await fetchTutorAccountApplications(status, page)); } catch (reason) { setError(formatErrorMessage(reason instanceof Error ? reason.message : "", "Не удалось загрузить заявки")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [status, page]);
  async function approve(id: number) { setBusy(id); try { await approveTutorAccountApplication(id); await load(); } catch (reason) { setError(formatErrorMessage(reason instanceof Error ? reason.message : "", "Не удалось одобрить заявку")); } finally { setBusy(null); } }
  async function reject(id: number) { const reason = window.prompt("Укажите причину отклонения"); if (!reason?.trim()) return; setBusy(id); try { await rejectTutorAccountApplication(id, reason); await load(); } catch (value) { setError(formatErrorMessage(value instanceof Error ? value.message : "", "Не удалось отклонить заявку")); } finally { setBusy(null); } }
  return <section><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Заявки на аккаунт репетитора</h2><p className="text-sm text-muted-foreground">Проверяйте данные пользователя до создания аккаунта.</p></div><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-xl border border-border bg-input-background px-3 py-2 text-sm"><option value="PENDING">На рассмотрении</option><option value="APPROVED">Одобрены</option><option value="REJECTED">Отклонены</option><option value="">Все</option></select></div>{error && <div className="mb-4 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{loading ? <div className="flex justify-center py-12"><Loader2 className="animate-spin" /></div> : <div className="space-y-3">{data.items.map((item) => <article key={item.id} className="rounded-2xl border border-border p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{item.fullName}</div><div className="text-sm text-muted-foreground">{item.email} · {item.age} лет</div></div><div className="font-medium">{item.pricePerLesson.toLocaleString("ru-RU")} ₽/час</div></div><div className="mt-3 text-sm">Предметы: {item.subjects.join(", ")}</div>{item.rejectionReason && <div className="mt-3 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{item.rejectionReason}</div>}{item.status === "PENDING" && <div className="mt-4 flex gap-2"><button disabled={busy === item.id} onClick={() => void approve(item.id)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm text-primary-foreground"><Check size={15} />Принять</button><button disabled={busy === item.id} onClick={() => void reject(item.id)} className="inline-flex items-center gap-2 rounded-xl border border-destructive/30 px-4 py-2 text-sm text-destructive"><X size={15} />Отклонить</button></div>}</article>)}{!data.items.length && <div className="py-10 text-center text-sm text-muted-foreground">Заявок нет</div>}</div>}<AdminPagination page={data.page} totalPages={data.totalPages} onChange={setPage} /></section>;
}
